from __future__ import annotations

"""Encounter-domain service catalog descriptors.

Metadata only. These entries document encounter truth, explicit overlays, provider
selection evidence, execution-method semantics, and read-only guide/projection layers
without making the catalog a runtime service locator.
"""

from services.service_catalog import EvidenceClass, ServiceBehavior, ServiceDescriptor


ENCOUNTER_SERVICE_DESCRIPTORS: tuple[ServiceDescriptor, ...] = (
    ServiceDescriptor(
        service_id="encounter.domain_read_model",
        domain="encounter",
        purpose="Expose read-only canonical encounter definitions, structured player requirements, target/positioning constraints, and reconciled evidence without inferring mechanics from prose.",
        implementation_path="services.encounter_service",
        inputs=("EncounterRepository", "EncounterId", "Difficulty", "PhaseId"),
        outputs=("EncounterDefinition", "EncounterRequirement", "EncounterTargetConstraint", "EncounterPositioningConstraint", "EncounterTemporalEvidence"),
        dependencies=("encounter.repository",),
        responsibilities=("canonical_encounter_domain_read_model",),
        behavior=ServiceBehavior.DETERMINISTIC,
        ui_safe=True,
        encounter_aware=True,
        evidence_class=EvidenceClass.GAME_MECHANIC,
        notes="Only explicit structured fields become requirements or constraints. Missing target counts, unresolved thresholds, prose hints, and source conflicts remain unresolved rather than being guessed into canonical truth.",
    ),
    ServiceDescriptor(
        service_id="encounter.requirement_overlay",
        domain="encounter",
        purpose="Append explicitly supplied analysis-context requirements to canonical encounter requirements without mutating or replacing the canonical encounter source.",
        implementation_path="services.encounter_requirement_overlay",
        inputs=("EncounterService", "ExplicitAdditionalRequirements"),
        outputs=("EncounterRequirement",),
        dependencies=("encounter.domain_read_model",),
        responsibilities=("explicit_encounter_requirement_overlay",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.POLICY,
        notes="The canonical encounter service remains authoritative for boss mechanics. Overlay requirements must come from another explicit source and may not collide with canonical requirement identities.",
    ),
    ServiceDescriptor(
        service_id="encounter.provider.candidate_projection",
        domain="encounter",
        purpose="Project authoritative Phase 10 provider evidence into exact per-requirement Phase 11 candidate sets without rescanning builds or choosing a provider.",
        implementation_path="services.encounter_provider_candidate",
        inputs=("EncounterRosterEvaluationReport", "SavedBuildCapabilityAudit"),
        outputs=("ProviderCandidateSet",),
        dependencies=("build.saved_capability_analysis",),
        responsibilities=("encounter_provider_candidate_projection",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.MIXED,
        notes="Provider, unresolved, and conflict membership from Phase 10 is authoritative. This layer binds that exact evidence to canonical requirements; names, tooltip prose, roster order, and fresh build inference are not substitutes.",
    ),
    ServiceDescriptor(
        service_id="encounter.provider.suitability",
        domain="encounter",
        purpose="Aggregate explicit source-backed suitability facts for already-viable provider candidates without changing capability truth or selecting a provider.",
        implementation_path="services.encounter_provider_suitability",
        inputs=("ProviderCandidateSet", "ProviderSuitabilityEvidence"),
        outputs=("ProviderSuitabilitySet",),
        dependencies=("encounter.provider.candidate_projection",),
        responsibilities=("encounter_provider_suitability_assessment",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.POLICY,
        notes="Suitability is not capability. Favorable Phase 11 facts cannot make unresolved or conflicting Phase 10 candidates viable; conflicting assessments for the same dimension are rejected rather than collapsed.",
    ),
    ServiceDescriptor(
        service_id="encounter.provider.assignment",
        domain="encounter",
        purpose="Choose primary encounter providers only when capability and optional suitability evidence leave a unique defensible assignment, otherwise preserve the unresolved state.",
        implementation_path="services.encounter_provider_assignment",
        inputs=("ProviderCandidateSet", "ProviderSuitabilitySet"),
        outputs=("ProviderAssignment",),
        dependencies=("encounter.provider.candidate_projection", "encounter.provider.suitability"),
        responsibilities=("encounter_provider_assignment",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.POLICY,
        notes="Roster order is never a tie-break. Unknown suitability is not a silent positive, conflicting capability blocks assignment, and ambiguous selections remain unresolved instead of being guessed.",
    ),
    ServiceDescriptor(
        service_id="encounter.provider.responsibility_audit",
        domain="encounter",
        purpose="Audit assigned providers for explicit source-backed double-duty conflicts between exact encounter requirements.",
        implementation_path="services.encounter_provider_responsibility",
        inputs=("ProviderAssignment", "ProviderResponsibilityConflictEvidence"),
        outputs=("ProviderResponsibilityAudit",),
        dependencies=("encounter.provider.assignment",),
        responsibilities=("encounter_provider_responsibility_conflict_audit",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.POLICY,
        notes="A player appearing on multiple provider rows is not itself a conflict. Double-duty conflicts exist only when explicit evidence says the same member cannot carry the exact pair of requirements together.",
    ),
    ServiceDescriptor(
        service_id="encounter.boss_guide.read_model",
        domain="encounter",
        purpose="Project persisted encounter identity, health, abilities, structural phases, and reviewed canonical timeline facts into a UI-ready read-only boss guide.",
        implementation_path="services.encounter_boss_guide",
        inputs=("CanonicalEncounterDatabase", "EncounterId"),
        outputs=("EncounterBossGuide", "BossGuideEncounterSummary"),
        responsibilities=("encounter_boss_guide_read_model",),
        behavior=ServiceBehavior.DETERMINISTIC,
        ui_safe=True,
        encounter_aware=True,
        evidence_class=EvidenceClass.GAME_MECHANIC,
        notes="Reviewed canonical timeline facts take precedence over structural phase rows only when present. Missing semantics are not invented, and malformed persisted canonical facts fail explicitly.",
    ),
    ServiceDescriptor(
        service_id="encounter.guide.evidence_projection",
        domain="encounter",
        purpose="Project reviewed encounter evidence, common raid names, and mitigation guidance into UI-ready fallback timeline and strategy rows without mutating canonical encounter truth.",
        implementation_path="services.encounter_guide_evidence_projection_service",
        inputs=("EncounterEvidencePacket", "ReferenceMitigation", "ReferenceCommonName"),
        outputs=("EncounterGuideEvidenceProjection", "EncounterGuideTimelineRow", "EncounterGuideStrategyRow"),
        dependencies=("encounter.boss_guide.read_model",),
        responsibilities=("reviewed_encounter_guide_evidence_projection",),
        behavior=ServiceBehavior.DETERMINISTIC,
        ui_safe=True,
        encounter_aware=True,
        evidence_class=EvidenceClass.MIXED,
        notes="Canonical boss-guide phases remain authoritative. Reviewed evidence supplies timeline rows only when canonical phases are absent and supplies strategy presentation without promoting guide text into canonical encounter mechanics.",
    ),
    ServiceDescriptor(
        service_id="encounter.execution.cleanse_method",
        domain="encounter",
        purpose="Resolve how explicit cleanse mechanics are handled from source-qualified structured encounter evidence without inferring methods from prose or player skill availability.",
        implementation_path="services.encounter_cleanse_method",
        inputs=("EncounterEvidenceFact",),
        outputs=("EncounterCleanseMethod",),
        dependencies=("encounter.domain_read_model",),
        responsibilities=("encounter_cleanse_method_resolution",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.GAME_MECHANIC,
        notes="A generic requires_cleanse flag does not prove which cleanse method works. Legacy cleanse-pool evidence may establish an encounter interaction but does not prove ordinary player cleanse skills are effective.",
    ),
    ServiceDescriptor(
        service_id="encounter.execution.interrupt_method",
        domain="encounter",
        purpose="Resolve encounter interrupt methods with explicit encounter evidence overriding the sourced ESO-wide standard bash rule.",
        implementation_path="services.encounter_interrupt_method",
        inputs=("EncounterEvidenceFact", "StandardInterruptRule"),
        outputs=("EncounterInterruptMethod",),
        dependencies=("encounter.domain_read_model",),
        responsibilities=("encounter_interrupt_method_resolution",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.GAME_MECHANIC,
        notes="Encounter-specific evidence wins even when unresolved or conflicting; uncertainty suppresses the generic bash fallback rather than being overwritten by it.",
    ),
    ServiceDescriptor(
        service_id="encounter.execution.method",
        domain="encounter",
        purpose="Resolve coarse movement and positioning handling methods from exact structured evidence without inventing coordinates, assignments, or raid choreography.",
        implementation_path="services.encounter_execution_method",
        inputs=("EncounterEvidenceFact",),
        outputs=("EncounterExecutionMethod",),
        dependencies=("encounter.domain_read_model",),
        responsibilities=("encounter_execution_method_resolution",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.GAME_MECHANIC,
        notes="Generic movement/positioning flags establish demand only, not strategy. Narrow legacy mappings are accepted only for exact structured fields already present in reconciled evidence.",
    ),
    ServiceDescriptor(
        service_id="encounter.execution.availability",
        domain="encounter",
        purpose="Resolve difficulty-specific availability of known encounter interactions from structured evidence without inventing alternate solutions.",
        implementation_path="services.encounter_execution_availability",
        inputs=("EncounterEvidenceFact", "EncounterDifficulty"),
        outputs=("EncounterExecutionAvailability",),
        dependencies=("encounter.domain_read_model", "encounter.execution.method"),
        responsibilities=("encounter_execution_availability_resolution",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.GAME_MECHANIC,
        notes="When evidence disables a known interaction and no alternate is proven, availability remains unknown rather than fabricating a replacement strategy.",
    ),
    ServiceDescriptor(
        service_id="encounter.health_threshold.clock_projection",
        domain="encounter",
        purpose="Project reviewed encounter health-threshold facts into clock times using explicit caller-supplied raid damage trajectories.",
        implementation_path="services.encounter_health_threshold_projection_service",
        inputs=("EncounterBossGuide", "Difficulty", "RaidDamageSegment"),
        outputs=("EncounterHealthThresholdProjection", "EncounterThresholdClockPoint"),
        dependencies=("encounter.boss_guide.read_model",),
        responsibilities=("encounter_health_threshold_clock_projection",),
        behavior=ServiceBehavior.DETERMINISTIC,
        encounter_aware=True,
        evidence_class=EvidenceClass.MIXED,
        notes="Encounter facts own threshold truth and boss-guide persistence owns health text. Raid DPS must be explicit caller input; single-event build potency or candidate-ranking metrics are never substituted for raid damage trajectory.",
    ),
    ServiceDescriptor(
        service_id="encounter.position_gif.frame_plan",
        domain="encounter",
        purpose="Build deterministic fixed-rate frame plans for Raid Map GIF exports while leaving pixel rendering to the UI layer.",
        implementation_path="services.encounter_position_gif_export_service",
        inputs=("PositionTimeline", "FramesPerSecond", "HoldSeconds"),
        outputs=("GifFrameSpec",),
        responsibilities=("encounter_position_gif_frame_planning",),
        behavior=ServiceBehavior.DETERMINISTIC,
        ui_safe=True,
        encounter_aware=True,
        evidence_class=EvidenceClass.NONE,
        notes="This service owns export timing only. It does not create encounter truth, infer positions, or render pixels; frame timing is deterministic and independent of wall-clock timers.",
    ),
)


__all__ = ["ENCOUNTER_SERVICE_DESCRIPTORS"]
